language: python

python:
  - "3.6"

services:
  - docker

jobs:
  include:
    - stage: test
      install: pip install -r requirements.txt
      script: 
	    - cd tests
        - pytest
    - stage: deploy
      before_install: 
	    - docker build -t bilalbox/panos_rule_exporter
      script: 
	    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bilalbox/panos_rule_exporter

